# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint

import six


class Tool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'point': 'Point',
        'rotation': 'Rotation',
        'radius': 'float'
    }

    attribute_map = {
        'name': 'name',
        'point': 'point',
        'rotation': 'rotation',
        'radius': 'radius'
    }

    def __init__(self, name=None, point=None, rotation=None, radius=None):  # noqa: E501
        """Tool - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._point = None
        self._rotation = None
        self._radius = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if point is not None:
            self.point = point
        if rotation is not None:
            self.rotation = rotation
        if radius is not None:
            self.radius = radius

    @property
    def name(self):
        """Gets the name of this Tool.  # noqa: E501


        :return: The name of this Tool.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tool.


        :param name: The name of this Tool.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def point(self):
        """Gets the point of this Tool.  # noqa: E501


        :return: The point of this Tool.  # noqa: E501
        :rtype: Point
        """
        return self._point

    @point.setter
    def point(self, point):
        """Sets the point of this Tool.


        :param point: The point of this Tool.  # noqa: E501
        :type: Point
        """

        self._point = point

    @property
    def rotation(self):
        """Gets the rotation of this Tool.  # noqa: E501


        :return: The rotation of this Tool.  # noqa: E501
        :rtype: Rotation
        """
        return self._rotation

    @rotation.setter
    def rotation(self, rotation):
        """Sets the rotation of this Tool.


        :param rotation: The rotation of this Tool.  # noqa: E501
        :type: Rotation
        """

        self._rotation = rotation

    @property
    def radius(self):
        """Gets the radius of this Tool.  # noqa: E501

        (in meters)  # noqa: E501

        :return: The radius of this Tool.  # noqa: E501
        :rtype: float
        """
        return self._radius

    @radius.setter
    def radius(self, radius):
        """Sets the radius of this Tool.

        (in meters)  # noqa: E501

        :param radius: The radius of this Tool.  # noqa: E501
        :type: float
        """

        self._radius = radius

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
