# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint

import six

from pulserest.client.models.capsule_obstacle import CapsuleObstacle
from pulserest.client.models.position import Position


class Tool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'tcp': 'Position',
        'shape': 'list[CapsuleObstacle]'
    }

    attribute_map = {
        'name': 'name',
        'tcp': 'tcp',
        'shape': 'shape'
    }

    def __init__(self, name=None, tcp=None, shape=None):  # noqa: E501
        """Tool - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._tcp = None
        self._shape = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if tcp is not None:
            self.tcp = tcp
        if shape is not None:
            self.shape = shape

    @property
    def name(self):
        """Gets the name of this Tool.  # noqa: E501


        :return: The name of this Tool.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tool.


        :param name: The name of this Tool.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tcp(self):
        """Gets the tcp of this Tool.  # noqa: E501


        :return: The tcp of this Tool.  # noqa: E501
        :rtype: Position
        """
        return self._tcp

    @tcp.setter
    def tcp(self, tcp):
        """Sets the tcp of this Tool.


        :param tcp: The tcp of this Tool.  # noqa: E501
        :type: Position
        """

        self._tcp = tcp

    @property
    def shape(self):
        """Gets the shape of this Tool.  # noqa: E501


        :return: The shape of this Tool.  # noqa: E501
        :rtype: list[CapsuleObstacle]
        """
        return self._shape

    @shape.setter
    def shape(self, shape):
        """Sets the shape of this Tool.


        :param shape: The shape of this Tool.  # noqa: E501
        :type: list[CapsuleObstacle]
        """

        self._shape = shape

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Tool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
